package: cloud.lazycat.app.pdf-math-translate-next
license: AGPL-3.0
version: 2.9.0
name: PDFMathTranslate Next
description: PDFMathTranslate 是一款强大的 PDF 翻译工具。
min_os_version: 1.5.0
homepage: https://github.com/PDFMathTranslate/PDFMathTranslate-next
author: PDFMathTranslate
permissions:
  required:
    - net.internet
locales:
  zh:
    name: PDFMathTranslate Next
    description: PDFMathTranslate 是一款强大的 PDF 翻译工具。
  zh_CN:
    name: PDFMathTranslate Next
    description: PDFMathTranslate 是一款强大的 PDF 翻译工具。
  en:
    name: PDFMathTranslate Next
    description: PDFMathTranslate is a powerful PDF translation tool.
